[build]
  publish = "."
  command = "npm test"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/favicon.svg"
  [headers.values]
    Cache-Control = "no-store"
