[build]
  publish = "."
  command = "npm test"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/js/gcData.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/js/specialVendorData.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/js/itemMeta.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"
